# Form implementation generated from reading ui file 'c:\Projects\Constrictor\FPE\ui\QtWatcherInfoDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QtWatcherInfoDialog(object):
    def setupUi(self, QtWatcherInfoDialog):
        QtWatcherInfoDialog.setObjectName("QtWatcherInfoDialog")
        QtWatcherInfoDialog.resize(682, 484)
        self.formLayoutWidget = QtWidgets.QWidget(parent=QtWatcherInfoDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 661, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(parent=self.formLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.frame)
        self.watcher_info_config = QtWidgets.QPlainTextEdit(parent=self.formLayoutWidget)
        self.watcher_info_config.setObjectName("watcher_info_config")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.watcher_info_config)
        self.watcher_info_status = QtWidgets.QPlainTextEdit(parent=self.formLayoutWidget)
        self.watcher_info_status.setObjectName("watcher_info_status")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.watcher_info_status)
        self.pushButton = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton)
        self.watcher_info_status.raise_()
        self.frame.raise_()
        self.watcher_info_config.raise_()
        self.pushButton.raise_()

        self.retranslateUi(QtWatcherInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(QtWatcherInfoDialog)

    def retranslateUi(self, QtWatcherInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        QtWatcherInfoDialog.setWindowTitle(_translate("QtWatcherInfoDialog", "Dialog"))
        self.pushButton.setText(_translate("QtWatcherInfoDialog", "PushButton"))
